version: '3'

services:
  nginx:
    image: markoshust/magento-nginx:1.18-8
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - ./src/config:/var/www/html/config:cached
      - ./src/web/app:/var/www/html/web/app:cached
      - ./src/web/index.php:/var/www/html/web/index.php:cached
      - ./src/web/wp-config.php:/var/www/html/web/wp-config.php:cached
      - ./.docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:cached
      - wpdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: alexleon/wp-php:8.3-fpm
    restart: always
    env_file: .env
    volumes: *appvolumes

  db:
    image: percona:8
    restart: always
    ports:
      - "13306:3306"
    env_file: .env
    volumes:
      - wpdbdata:/var/lib/mysql

  memcached:
    image: memcached:latest
    restart: always

volumes:
  wpdata:
  wpdbdata:
  sockdata:
  ssldata:
